import { StyleSheet } from 'react-native';
import { colors, radii, shadows, spacing } from '../../theme/colors';

export const financeStyles = StyleSheet.create({
  errorCard: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderRadius: radii.md, padding: spacing.md, backgroundColor: colors.dangerBg },
  errorText: { flex: 1, color: colors.dangerText, fontSize: 13, lineHeight: 18 },
  hero: { padding: spacing.lg, gap: spacing.lg }, heroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  heroEyebrow: { color: colors.ink950, fontSize: 11, fontWeight: '700', letterSpacing: 1 }, heroValue: { color: colors.ink950, fontSize: 29, fontWeight: '800', marginTop: spacing.xs },
  walletIcon: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.48)' },
  summaryRow: { flexDirection: 'row', borderRadius: radii.md, padding: spacing.md, backgroundColor: 'rgba(255,255,255,0.52)' },
  summaryItem: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, summaryDivider: { width: 1, marginHorizontal: spacing.sm, backgroundColor: 'rgba(15,17,21,0.12)' },
  summaryLabel: { color: colors.textSecondary, fontSize: 11 }, summaryValue: { color: colors.ink950, fontSize: 13, fontWeight: '700' },
  actionsRow: { flexDirection: 'row', gap: spacing.sm }, primaryAction: { flex: 1, minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, borderRadius: radii.md, backgroundColor: colors.ink950, ...shadows.card },
  primaryActionText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' }, secondaryAction: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card },
  card: { borderRadius: radii.lg, borderWidth: 1, borderColor: colors.border, padding: spacing.lg, backgroundColor: colors.card, ...shadows.sm }, cardTitle: { color: colors.text, fontSize: 16, fontWeight: '700', marginBottom: spacing.md },
  chartContent: { flexDirection: 'row', alignItems: 'center', gap: spacing.lg }, donutCenter: { position: 'absolute', inset: 0, alignItems: 'center', justifyContent: 'center' }, donutCaption: { color: colors.textSecondary, fontSize: 10, fontWeight: '600', marginBottom: 2 },
  legend: { flex: 1, gap: spacing.md }, legendRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, legendDot: { width: 9, height: 9, borderRadius: 5 }, legendLabel: { flex: 1, color: colors.textSecondary, fontSize: 12 }, legendValue: { color: colors.text, fontSize: 12, fontWeight: '700' },
  segmented: { flexDirection: 'row', gap: spacing.xs, borderRadius: radii.md, padding: spacing.xs, backgroundColor: colors.surfaceSubtle }, segment: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radii.sm }, segmentActive: { backgroundColor: colors.card, ...shadows.sm }, segmentText: { color: colors.textSecondary, fontSize: 13, fontWeight: '600' }, segmentTextActive: { color: colors.gold700, fontWeight: '800' },
  searchInput: { minHeight: 48, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.lg, color: colors.text, backgroundColor: colors.card }, movementsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sectionTitle: { color: colors.text, fontSize: 17, fontWeight: '700' }, countText: { minWidth: 28, textAlign: 'center', paddingVertical: 4, paddingHorizontal: 8, borderRadius: radii.full, color: colors.gold700, fontSize: 12, fontWeight: '700', backgroundColor: colors.gold100 },
  movementCard: { minHeight: 86, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.border, padding: spacing.md, backgroundColor: colors.card, ...shadows.sm }, movementIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' }, inIcon: { backgroundColor: colors.success100 }, outIcon: { backgroundColor: colors.danger100 }, movementBody: { flex: 1, minWidth: 0, gap: 2 }, movementTitle: { color: colors.text, fontSize: 14, fontWeight: '700' }, movementMeta: { color: colors.textSecondary, fontSize: 12 }, statusText: { fontSize: 11, fontWeight: '600' }, statusConfirmed: { color: colors.success600 }, statusPlanned: { color: colors.warningText }, movementRight: { alignItems: 'flex-end', gap: spacing.sm }, amountText: { fontSize: 13, fontWeight: '800' }, amountIn: { color: colors.success600 }, amountOut: { color: colors.text },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15,17,21,0.45)' }, modalDismissArea: { flex: 1 }, sheet: { maxHeight: '90%', gap: spacing.md, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingTop: spacing.sm, paddingHorizontal: spacing.lg, backgroundColor: colors.background }, categorySheet: { maxHeight: '78%' }, sheetHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: colors.borderStrong }, sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sheetTitle: { color: colors.text, fontSize: 21, fontWeight: '800' }, sheetSubtitle: { color: colors.textSecondary, fontSize: 12, marginTop: 2 }, formContent: { gap: spacing.md, paddingBottom: spacing.xl },
  fieldGroup: { gap: 6 }, fieldLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: '700' }, input: { minHeight: 48, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md, color: colors.text, fontSize: 14, backgroundColor: colors.card }, textarea: { minHeight: 84, paddingTop: spacing.md, textAlignVertical: 'top' }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, chip: { minHeight: 38, justifyContent: 'center', borderRadius: radii.full, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md, backgroundColor: colors.card }, chipActive: { borderColor: colors.gold600, backgroundColor: colors.gold100 }, chipText: { color: colors.textSecondary, fontSize: 12, fontWeight: '600' }, chipTextActive: { color: colors.gold700, fontWeight: '700' },
  attachmentButton: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderRadius: radii.md, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.gold600, paddingHorizontal: spacing.md, backgroundColor: colors.gold50 }, attachmentText: { flex: 1, color: colors.gold700, fontSize: 12, fontWeight: '700' }, saveButton: { minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: radii.md, backgroundColor: colors.ink950 }, saveButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' }, disabled: { opacity: 0.5 },
  categoryList: { marginTop: spacing.xs }, categoryRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border }, categoryDot: { width: 10, height: 10, borderRadius: 5 }, categoryName: { flex: 1, color: colors.text, fontSize: 14, fontWeight: '600' }, categoryType: { color: colors.textSecondary, fontSize: 12 },
  onboardingBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.lg, backgroundColor: 'rgba(15,17,21,0.55)' }, onboardingCard: { width: '100%', maxWidth: 420, gap: spacing.lg, borderRadius: 24, padding: spacing.xl, backgroundColor: colors.card, ...shadows.elevated }, onboardingIcon: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.gold100 }, onboardingText: { color: colors.textSecondary, fontSize: 14, lineHeight: 20 },
});
