export type FunnelStage = 'lead' | 'contato_inicial' | 'proposta_enviada' | 'negociacao' | 'cliente_fechado' | 'cliente_perdido';
export type FunnelMetrics = Record<FunnelStage, number> & { total: number };
export type PipelineForecastItem = { stage: string; count: number; weighted_value: number };
export type AnalyticsClient = { id: string; stage: string | null; budget_expected: number | null };
export const STAGE_LABELS: Record<string, string> = { lead: 'Lead', contato_inicial: 'Contato Inicial', proposta_enviada: 'Proposta Enviada', negociacao: 'Negociação', cliente_fechado: 'Cliente Fechado', cliente_perdido: 'Cliente Perdido' };
export const ANALYTICS_STAGE_ORDER: FunnelStage[] = ['lead', 'contato_inicial', 'proposta_enviada', 'negociacao', 'cliente_fechado'];
export const FUNNEL_OPACITY: Record<number, number> = { 0: 1, 1: .82, 2: .64, 3: .48, 4: .34 };
export const EMPTY_FUNNEL: FunnelMetrics = { lead: 0, contato_inicial: 0, proposta_enviada: 0, negociacao: 0, cliente_fechado: 0, cliente_perdido: 0, total: 0 };
export function toBRL(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value || 0); }
export function normalizeAnalyticsStage(raw?: string | null): FunnelStage { const stage = raw?.trim().toLowerCase() ?? 'lead'; if (stage in EMPTY_FUNNEL && stage !== 'total') return stage as FunnelStage; return ({ conhecendo_cliente: 'lead', analisando_orcamento: 'proposta_enviada', assinatura_contrato: 'negociacao', won: 'cliente_fechado', lost: 'cliente_perdido' } as Record<string, FunnelStage>)[stage] ?? 'lead'; }
export function fallbackAnalytics(clients: AnalyticsClient[]) { const funnel = { ...EMPTY_FUNNEL }, buckets: Record<string, { count: number; value: number }> = {}; for (const client of clients) { const stage = normalizeAnalyticsStage(client.stage); funnel[stage] += 1; if (stage !== 'cliente_perdido') { buckets[stage] ??= { count: 0, value: 0 }; buckets[stage].count += 1; buckets[stage].value += Number(client.budget_expected ?? 0); } } funnel.total = Object.entries(funnel).filter(([key]) => key !== 'total').reduce((sum, [, value]) => sum + value, 0); const weights: Record<string, number> = { lead: .1, contato_inicial: .25, proposta_enviada: .45, negociacao: .7, cliente_fechado: 1 }; const forecast = ANALYTICS_STAGE_ORDER.filter((stage) => buckets[stage]).map((stage) => ({ stage, count: buckets[stage].count, weighted_value: buckets[stage].value * weights[stage] })); return { funnel, forecast }; }
export function parseFunnel(raw: Record<string, unknown>): FunnelMetrics { return { lead: Number(raw.lead ?? 0), contato_inicial: Number(raw.contato_inicial ?? 0), proposta_enviada: Number(raw.proposta_enviada ?? 0), negociacao: Number(raw.negociacao ?? 0), cliente_fechado: Number(raw.cliente_fechado ?? 0), cliente_perdido: Number(raw.cliente_perdido ?? 0), total: Number(raw.total ?? 0) }; }
export function parseForecast(raw: Array<Record<string, unknown>>): PipelineForecastItem[] { return raw.map((item) => ({ stage: String(item.stage ?? ''), count: Number(item.count ?? 0), weighted_value: Number(item.weighted_value ?? 0) })); }
export function analyticsPresentation(funnel: FunnelMetrics, forecast: PipelineForecastItem[]) { const maxFunnelValue = Math.max(...ANALYTICS_STAGE_ORDER.map((stage) => funnel[stage]), 1), totalWeighted = forecast.reduce((sum, item) => sum + item.weighted_value, 0), conversionLeadToClosed = funnel.lead ? ((funnel.cliente_fechado / funnel.lead) * 100).toFixed(1) : '0,0', perStageRates = ANALYTICS_STAGE_ORDER.slice(0, -1).map((from, index) => { const to = ANALYTICS_STAGE_ORDER[index + 1]; return { from, to, rate: funnel[from] ? ((funnel[to] / funnel[from]) * 100).toFixed(1) : '0,0' }; }); return { maxFunnelValue, totalWeighted, conversionLeadToClosed, perStageRates }; }
