import { StyleSheet } from 'react-native';
import { colors, shadows } from '../../theme/colors';

export const meetingStyles = StyleSheet.create({
  container: { gap: 16 },
  loadingBox: { minHeight: 180, alignItems: 'center', justifyContent: 'center', gap: 10 },
  hero: {
    backgroundColor: colors.ink950,
    borderRadius: 18,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    ...shadows.card,
  },
  heroIcon: { width: 46, height: 46, borderRadius: 14, backgroundColor: colors.gold50, alignItems: 'center', justifyContent: 'center' },
  heroCopy: { flex: 1, gap: 3 },
  heroTitle: { color: '#FFFFFF', fontSize: 17, fontWeight: '800' },
  heroText: { color: '#D1D5DB', fontSize: 12, lineHeight: 17 },
  scheduleButton: { minHeight: 38, paddingHorizontal: 11, borderRadius: 11, backgroundColor: colors.primaryStrong, flexDirection: 'row', alignItems: 'center', gap: 4 },
  scheduleButtonText: { color: colors.primaryTextOn, fontSize: 12, fontWeight: '800' },
  refreshRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  errorText: { color: colors.dangerText, backgroundColor: colors.dangerBg, borderRadius: 10, padding: 10, fontSize: 13, fontWeight: '600' },
  section: { gap: 10 },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  sectionTitle: { color: colors.textSecondary, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7 },
  liveTitle: { color: colors.dangerText },
  liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.dangerText },
  meetingCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 14, gap: 12, ...shadows.sm },
  meetingCardLive: { borderColor: '#F3B4B4', backgroundColor: '#FFFDFD' },
  cardHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  cardHeadingCopy: { flex: 1, gap: 3 },
  cardTitle: { color: colors.text, fontSize: 15, fontWeight: '800' },
  muted: { color: colors.mutedText, fontSize: 12, lineHeight: 17 },
  statusPill: { backgroundColor: colors.primarySoft, borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 },
  statusPillDanger: { backgroundColor: colors.dangerBg },
  statusText: { color: colors.primaryStrong, fontSize: 10, fontWeight: '800' },
  statusTextDanger: { color: colors.dangerText },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  actionButton: { minHeight: 38, borderRadius: 10, borderWidth: 1, borderColor: colors.borderStrong, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, flexGrow: 1 },
  actionButtonPrimary: { borderColor: colors.primaryStrong, backgroundColor: colors.primaryStrong },
  actionButtonDanger: { borderColor: '#F3B4B4', backgroundColor: colors.dangerBg },
  actionButtonText: { color: colors.primaryStrong, fontSize: 12, fontWeight: '800' },
  actionButtonTextPrimary: { color: colors.primaryTextOn },
  actionButtonTextDanger: { color: colors.dangerText },
  disabled: { opacity: 0.55 },
  notesBox: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border, paddingTop: 12, gap: 8 },
  inputLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: '700' },
  input: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.text, borderRadius: 11, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14 },
  notesInput: { minHeight: 92 },
  historyCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 13, gap: 11 },
  historyTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  historyCopy: { flex: 1, gap: 3 },
  processingText: { color: colors.mutedText, fontSize: 12, lineHeight: 18 },
  emptyBox: { minHeight: 86, backgroundColor: colors.surfaceSubtle, borderRadius: 14, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', padding: 16, gap: 7 },
  emptyText: { color: colors.mutedText, fontSize: 12, textAlign: 'center' },
  refreshButton: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8 },
  refreshButtonText: { color: colors.primaryStrong, fontSize: 12, fontWeight: '700' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(15,17,21,0.55)', justifyContent: 'center', paddingHorizontal: 20 },
  modalCard: { maxHeight: '84%', backgroundColor: colors.card, borderRadius: 18, overflow: 'hidden' },
  modalHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, padding: 18, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  modalTitle: { color: colors.text, fontSize: 19, fontWeight: '800' },
  modalContent: { padding: 18, gap: 9 },
  modalErrorText: { color: colors.dangerText, backgroundColor: colors.dangerBg, borderRadius: 10, padding: 10, fontSize: 12, fontWeight: '600' },
  helperText: { color: colors.mutedText, fontSize: 11 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 10 },
  cancelButton: { flex: 1, minHeight: 44, borderWidth: 1, borderColor: colors.border, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  cancelButtonText: { color: colors.textSecondary, fontSize: 14, fontWeight: '700' },
  confirmButton: { flex: 1, minHeight: 44, backgroundColor: colors.primaryStrong, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  confirmButtonText: { color: colors.primaryTextOn, fontSize: 14, fontWeight: '800' },
});
