import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const eventsScreenStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background, paddingHorizontal: 16, paddingBottom: 20 },
  centerPage: { flex: 1, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  title: { color: colors.text, fontSize: 28, fontWeight: '700' },
  subtitle: { color: colors.mutedText, fontSize: 14 },
  refreshRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  refreshText: { color: colors.mutedText, fontSize: 12, fontWeight: '600' },
  newButton: { height: 42, borderRadius: 10, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  newButtonText: { color: colors.primaryTextOn, fontWeight: '700', fontSize: 14 },
  filtersWrap: { gap: 8, marginBottom: 4 },
  listWrap: { flex: 1 },
  listContent: { gap: 10, paddingBottom: 20 },
  eventCard: { backgroundColor: colors.card, borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 10, gap: 6 },
  eventCover: { width: '100%', height: 120, borderRadius: 10 },
  eventName: { color: colors.text, fontSize: 16, fontWeight: '700' },
  eventMeta: { color: colors.mutedText, fontSize: 13 },
  eventStatus: { alignSelf: 'flex-start', marginTop: 4, backgroundColor: colors.primarySoft, color: colors.primaryStrong, fontSize: 11, fontWeight: '700', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, overflow: 'hidden' },
  emptyState: { paddingVertical: 40, alignItems: 'center', gap: 4 },
  emptyTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
  emptyText: { color: colors.mutedText, fontSize: 13 },
  errorBox: { backgroundColor: colors.dangerBg, borderRadius: 10, padding: 10, marginBottom: 10 },
  errorText: { color: colors.dangerText, fontSize: 13, textAlign: 'center', fontWeight: '600' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', padding: 20, justifyContent: 'center' },
  modalCard: { backgroundColor: colors.card, borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 16 },
  modalFormContent: { gap: 10, paddingBottom: 8 },
  modalTitle: { color: colors.text, fontSize: 20, fontWeight: '700', marginBottom: 4 },
  previewLabel: { color: colors.mutedText, fontSize: 12, fontWeight: '600' },
  previewImage: { width: '100%', height: 130, borderRadius: 10, borderWidth: 1, borderColor: colors.border },
  input: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, color: colors.text },
  typeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 2, marginBottom: 8 },
  typeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 2, marginBottom: 8 },
  typeCard: {
    width: '48%',
    height: 92,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'flex-end',
  },
  typeCardOn: {
    borderColor: colors.primaryStrong,
    borderWidth: 2,
  },
  typeImage: {
    ...StyleSheet.absoluteFillObject,
  },
  typeOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.28)',
  },
  typeCardText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    padding: 8,
  },
  typePill: { borderWidth: 1, borderColor: colors.border, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: colors.card },
  typePillSelected: { borderColor: colors.primaryStrong, backgroundColor: colors.primarySoft },
  typePillText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  dangerPill: { borderWidth: 1, borderColor: '#FECACA', backgroundColor: colors.dangerBg, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  dangerPillText: { color: colors.dangerText, fontSize: 12, fontWeight: '700' },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 6 },
  ghostButton: { flex: 1, borderWidth: 1, borderColor: colors.border, borderRadius: 10, alignItems: 'center', justifyContent: 'center', height: 44 },
  ghostButtonText: { color: colors.text, fontWeight: '600', fontSize: 14 },
  primaryButton: { flex: 1, backgroundColor: colors.primary, borderRadius: 10, alignItems: 'center', justifyContent: 'center', height: 44 },
  primaryButtonText: { color: colors.primaryTextOn, fontWeight: '700', fontSize: 14 },
  loadMore: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, minHeight: 40, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  loadMoreText: { color: colors.text, fontWeight: '600', fontSize: 13 },
});
