import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  financeTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  financePrivacyRow: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 16, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.border },
  directoryBlock: { gap: 10, padding: 14, borderRadius: 17, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.border },
  directoryTeam: { gap: 9, padding: 12, borderRadius: 14, backgroundColor: colors.card },
  directoryTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
  directoryLink: { color: colors.primaryStrong, fontSize: 12, fontWeight: '800' },
  directoryAssign: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10, backgroundColor: '#111318' },
  directoryAssignText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  directoryPeople: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  directoryPerson: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 999, borderWidth: 1, borderColor: colors.border },
  directoryPersonText: { color: colors.text, fontSize: 11, fontWeight: '700' },
  directoryEmpty: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 14, borderRadius: 16, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.border },
  page: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, gap: 10, paddingBottom: 28 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background },
  back: { color: colors.mutedText, fontWeight: '600', fontSize: 13 },
  p: { color: colors.textSecondary, fontSize: 14, lineHeight: 20 },
  card: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 10, gap: 8 },
  cardSoft: { backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 10, gap: 8 },
  heroCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 12, gap: 10 },
  heroTopRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  heroAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    overflow: 'hidden',
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroAvatarImage: { width: '100%', height: '100%' },
  heroAvatarFallback: { color: colors.primaryStrong, fontSize: 28, fontWeight: '800' },
  heroMetaWrap: { flex: 1, gap: 2 },
  heroActionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  commandCta: {
    borderRadius: 10,
    minHeight: 36,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DC2626',
  },
  commandCtaText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  grow: { flex: 1 },
  title: { color: colors.text, fontWeight: '700', fontSize: 22 },
  coverImage: { width: '100%', height: 164, borderRadius: 10 },
  meta: { color: colors.mutedText, fontSize: 13 },
  tabRow: { gap: 8, paddingVertical: 4 },
  tab: { paddingHorizontal: 10, paddingVertical: 7, borderWidth: 1, borderColor: colors.border, borderRadius: 999, backgroundColor: colors.card },
  tabOn: { borderColor: colors.primaryStrong, backgroundColor: colors.primarySoft },
  tabText: { color: colors.mutedText, fontWeight: '600', fontSize: 12 },
  tabTextOn: { color: colors.primaryStrong },
  err: { color: colors.dangerText, backgroundColor: colors.dangerBg, borderRadius: 8, padding: 8, textAlign: 'center' },
  loadingOverlay: { flex: 1, backgroundColor: colors.background, alignItems: 'stretch', justifyContent: 'center' },
  moduleContent: { gap: 10 },
  subtitle: { color: colors.text, fontWeight: '700', fontSize: 15 },
  overviewStack: { gap: 10 },
  alertsWrap: { gap: 6 },
  alertRow: { borderRadius: 10, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 8 },
  alertError: { borderColor: '#FECACA', backgroundColor: '#FEF2F2' },
  alertWarning: { borderColor: '#FDE68A', backgroundColor: '#FFFBEB' },
  alertInfo: { borderColor: '#BFDBFE', backgroundColor: '#EFF6FF' },
  alertText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  metricCard: {
    flexBasis: '48%',
    flexGrow: 1,
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    gap: 6,
    backgroundColor: colors.card,
  },
  metricPink: { borderColor: '#F9A8D4', backgroundColor: '#FDF2F8' },
  metricGold: { borderColor: '#FDE68A', backgroundColor: '#FFFBEB' },
  metricBlue: { borderColor: '#BFDBFE', backgroundColor: '#EFF6FF' },
  metricGreen: { borderColor: '#BBF7D0', backgroundColor: '#F0FDF4' },
  metricLabel: { color: colors.mutedText, fontSize: 11, fontWeight: '700', textTransform: 'uppercase' },
  metricValue: { color: colors.text, fontSize: 22, fontWeight: '800' },
  metricSub: { color: colors.text, fontSize: 12, fontWeight: '600' },
  metricTrack: { height: 8, borderRadius: 999, backgroundColor: '#E5E7EB', overflow: 'hidden' },
  metricFill: { height: '100%', borderRadius: 999 },
  metricEditWrap: { gap: 8 },
  overviewFinanceHero: {
    gap: 14,
    padding: 18,
    borderRadius: 22,
    backgroundColor: '#E8C75A',
    borderWidth: 1,
    borderColor: '#D2AC31',
    shadowColor: '#8A6812',
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 4,
    overflow: 'hidden',
  },
  overviewFinanceHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  overviewEyebrow: { color: '#6F5310', fontSize: 10, fontWeight: '900', letterSpacing: 0.8, textTransform: 'uppercase' },
  overviewFinanceTitle: { color: '#15120B', fontSize: 18, lineHeight: 23, fontWeight: '900' },
  overviewFinanceCopy: { color: '#5D4B20', fontSize: 12, lineHeight: 17, fontWeight: '600' },
  overviewMoneySplit: { flexDirection: 'row', padding: 12, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.62)' },
  overviewMoneyItem: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8 },
  overviewMoneyDivider: { width: 1, marginHorizontal: 10, backgroundColor: 'rgba(63,48,11,0.16)' },
  overviewMoneyDot: { width: 9, height: 9, borderRadius: 5 },
  overviewMoneyDotSpent: { backgroundColor: '#E11D48' },
  overviewMoneyDotAvailable: { backgroundColor: '#059669' },
  overviewMoneyLabel: { color: '#6B5A31', fontSize: 10, fontWeight: '700' },
  overviewMoneyValue: { color: '#17140C', fontSize: 12, fontWeight: '900' },
  overviewProgressTrack: { height: 7, overflow: 'hidden', borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.62)' },
  overviewProgressFill: { height: '100%', borderRadius: 999, backgroundColor: '#111318' },
  overviewFinanceActions: { flexDirection: 'row', gap: 10 },
  overviewSecondaryAction: { flex: 1, minHeight: 44, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center', borderRadius: 14, borderWidth: 1, borderColor: 'rgba(31,26,13,0.18)', backgroundColor: 'rgba(255,255,255,0.62)' },
  overviewSecondaryActionText: { color: '#17140C', fontSize: 12, fontWeight: '800' },
  overviewPrimaryAction: { flex: 1, minHeight: 44, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: '#111318' },
  overviewPrimaryActionText: { color: '#FFFFFF', fontSize: 12, fontWeight: '800' },
  overviewSectionHeading: { marginTop: 6, paddingHorizontal: 2 },
  overviewSectionTitle: { color: colors.text, fontSize: 17, fontWeight: '900' },
  overviewActionStack: { gap: 8 },
  overviewActionCard: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: 11, padding: 12, borderRadius: 17, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
  overviewActionIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  overviewActionIconRose: { backgroundColor: '#FCE7F3' },
  overviewActionIconBlue: { backgroundColor: '#DBEAFE' },
  overviewActionIconGreen: { backgroundColor: '#D1FAE5' },
  overviewActionTitle: { color: colors.text, fontSize: 14, fontWeight: '900' },
  overviewActionCopy: { color: colors.mutedText, fontSize: 11, lineHeight: 15 },
  overviewActionValueWrap: { alignItems: 'flex-end' },
  overviewActionValue: { color: colors.text, fontSize: 18, fontWeight: '900' },
  overviewActionUnit: { color: colors.mutedText, fontSize: 9, fontWeight: '700' },
  overviewActionCounter: { color: colors.text, fontSize: 14, fontWeight: '900' },
  chartRows: { gap: 8 },
  chartRowItem: { gap: 4 },
  chartLabel: { color: colors.text, fontSize: 12, fontWeight: '600' },
  chartValue: { color: colors.mutedText, fontSize: 12, fontWeight: '600' },
  chartTrack: { height: 8, borderRadius: 999, backgroundColor: '#ECEFF3', overflow: 'hidden' },
  chartFill: { height: '100%', borderRadius: 999 },
  segmentWrap: { gap: 6 },
  segmentTitle: { fontSize: 12, fontWeight: '700' },
  segmentError: { color: '#B91C1C' },
  segmentWarning: { color: '#B45309' },
  segmentInfo: { color: '#1D4ED8' },
  segmentNeutral: { color: '#4B5563' },
  segmentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 8,
    backgroundColor: '#FFFFFF',
  },
  commandTitle: { color: colors.text, fontWeight: '700', fontSize: 14, marginBottom: 2 },
  commandScoreWrap: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 10, gap: 6 },
  commandScoreLabel: { color: colors.mutedText, fontSize: 12, fontWeight: '600' },
  commandScoreValue: { color: colors.text, fontSize: 22, fontWeight: '700' },
  commandTrack: { height: 10, borderRadius: 999, backgroundColor: '#ECEFF3', overflow: 'hidden' },
  commandFill: { height: '100%', borderRadius: 999 },
  commandLine: { borderRadius: 10, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 8 },
  commandLow: { borderColor: '#BBF7D0', backgroundColor: '#F0FDF4' },
  commandMedium: { borderColor: '#FDE68A', backgroundColor: '#FFFBEB' },
  commandHigh: { borderColor: '#FECACA', backgroundColor: '#FEF2F2' },
  commandText: { color: colors.text, fontSize: 13, fontWeight: '600' },
  commandRulesCard: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 10, gap: 8, backgroundColor: '#F8FAFC' },
  commandRuleGrid: { flexDirection: 'row', gap: 8 },
  commandRuleInput: { flex: 1 },
  commandBlock: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 10, gap: 6, backgroundColor: colors.card },
  commandBlockTitle: { color: colors.text, fontWeight: '700', fontSize: 13 },
  commandItem: { color: colors.mutedText, fontSize: 12, fontWeight: '600' },
  commandSlaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  commandSeverity: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    overflow: 'hidden',
    fontSize: 10,
    fontWeight: '700',
  },
  commandSeverityCritical: { borderColor: '#FECACA', backgroundColor: '#FEF2F2', color: '#B91C1C' },
  commandSeverityWarning: { borderColor: '#FDE68A', backgroundColor: '#FFFBEB', color: '#92400E' },
  commandSeverityInfo: { borderColor: '#BFDBFE', backgroundColor: '#EFF6FF', color: '#1D4ED8' },
  commandVendorCard: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 8, gap: 4, backgroundColor: '#FFFFFF' },
  commandVendorName: { color: colors.text, fontSize: 13, fontWeight: '700' },
  commandVendorStatus: { color: colors.primaryStrong, fontSize: 11, fontWeight: '700' },
  commandIncidentCard: { borderWidth: 1, borderRadius: 10, padding: 8, gap: 4 },
  commandIncidentOpen: { borderColor: '#FECACA', backgroundColor: '#FEF2F2' },
  commandIncidentResolved: { borderColor: '#BBF7D0', backgroundColor: '#F0FDF4' },
  caption: { color: colors.mutedText, fontSize: 12, fontWeight: '600' },
  row: { color: colors.text, fontSize: 13 },
  historyVisualCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    padding: 10,
    gap: 10,
  },
  historyTrack: { height: 8, borderRadius: 999, backgroundColor: '#E5E7EB', overflow: 'hidden' },
  historyTrackFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#8B5CF6',
  },
  historyNodeRow: { gap: 8, paddingVertical: 2 },
  historyNode: {
    width: 180,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    padding: 8,
    gap: 3,
  },
  historyNodeSelected: { borderColor: '#8B5CF6', backgroundColor: '#F5F3FF' },
  historyNodeDot: { width: 10, height: 10, borderRadius: 999 },
  historyNodeDay: { color: colors.mutedText, fontSize: 11, fontWeight: '700' },
  historyNodeTitle: { color: colors.text, fontSize: 13, fontWeight: '700' },
  historyNodeDetail: { color: colors.mutedText, fontSize: 11 },
  historyList: { gap: 6 },
  historyItemRow: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: '#FFFFFF', padding: 8, gap: 2 },
  historyAt: { color: colors.mutedText, fontSize: 11, fontWeight: '700' },
  historyText: { color: colors.text, fontSize: 13 },
  input: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, color: colors.text },
  formLabel: { color: colors.text, fontSize: 13, fontWeight: '700', marginTop: 2 },
  formRow: { flexDirection: 'row', gap: 10 },
  formGrow: { flex: 1 },
  formDivider: { color: colors.mutedText, fontSize: 12, textAlign: 'center', marginVertical: 2 },
  activeFilter: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, borderRadius: 12, borderWidth: 1, borderColor: colors.gold200, backgroundColor: colors.gold50, paddingHorizontal: 12 },
  activeFilterText: { flex: 1, color: colors.gold700, fontSize: 12, fontWeight: '700' },
  uploadAction: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 14, borderWidth: 1, borderColor: colors.gold200, backgroundColor: colors.gold50, padding: 14 },
  uploadTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
  uploadSubtitle: { color: colors.textSecondary, fontSize: 12, marginTop: 2 },
  teamMemberWrap: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  teamPhotoButton: { width: 82, minHeight: 92, alignItems: 'center', justifyContent: 'center', gap: 5, borderRadius: 14, borderWidth: 1, borderColor: colors.gold200, backgroundColor: colors.gold50, overflow: 'hidden' },
  teamPhoto: { width: 82, height: 64, resizeMode: 'cover' },
  teamPhotoText: { color: colors.gold700, fontSize: 10, fontWeight: '700', textAlign: 'center' },
  inviteHero: { overflow: 'hidden', borderRadius: 18, borderWidth: 1, borderColor: colors.gold200, backgroundColor: colors.gold50 },
  inviteHeroImage: { width: '100%', height: 170, resizeMode: 'cover' },
  inviteHeroPlaceholder: { height: 130, alignItems: 'center', justifyContent: 'center', gap: 8 },
  inviteHeroActions: { gap: 10, padding: 12 },
  receptionHero: { alignItems: 'center', gap: 8, borderRadius: 18, borderWidth: 1, borderColor: colors.gold200, backgroundColor: colors.gold50, padding: 20 },
  area: { minHeight: 88, textAlignVertical: 'top' },
  btn: { backgroundColor: colors.primary, borderRadius: 8, minHeight: 38, alignItems: 'center', justifyContent: 'center' },
  btnText: { color: colors.primaryTextOn, fontWeight: '700' },
  item: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 8, gap: 6 },
  rowBtns: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  statsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  pill: { fontSize: 11, color: colors.primaryStrong, backgroundColor: colors.primarySoft, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4, overflow: 'hidden' },
  btnGhost: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, minHeight: 32, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center' },
  btnGhostWide: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, minHeight: 36, alignItems: 'center', justifyContent: 'center' },
  smallText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  btnDelete: { borderWidth: 1, borderColor: '#FECACA', backgroundColor: colors.dangerBg, borderRadius: 8, minHeight: 32, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center' },
  delText: { color: colors.dangerText, fontWeight: '700' },
  visualMapGrid: { gap: 8 },
  visualTableCard: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 10, gap: 6, backgroundColor: colors.card },
  visualTableName: { color: colors.text, fontSize: 14, fontWeight: '700' },
  visualTrack: { height: 10, borderRadius: 999, backgroundColor: '#ECEFF3', overflow: 'hidden' },
  visualFill: { height: '100%', borderRadius: 999 },
  compactPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  compactPickerIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primarySoft,
    marginRight: 10,
  },
  compactPickerTextGroup: {
    flex: 1,
    marginRight: 12,
  },
  compactPickerLabel: {
    fontSize: 11,
    color: colors.mutedText,
    textTransform: 'uppercase',
    fontWeight: '700',
    marginBottom: 2,
  },
  compactPickerValue: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  compactPickerAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  compactPickerActionText: {
    color: colors.primaryStrong,
    fontSize: 12,
    fontWeight: '700',
  },
});
