import { useCallback, useRef, useState } from 'react';
import { EVENTS_PAGE_SIZE, mergeEvents, type EventItem } from './eventsModel';
import { fetchEventsPage, resolveEventCover } from './eventsService';
export function useEventsData(userId?: string) {
  const [events, setEvents] = useState<EventItem[]>([]), [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [loadingMore, setLoadingMore] = useState(false), [error, setError] = useState(''), [page, setPage] = useState(-1), [hasMore, setHasMore] = useState(true);
  const loaded = useRef(false), lastLoadedAt = useRef(0), resetInFlight = useRef(false), appendInFlight = useRef(false), coverCache = useRef(new Map<string, string>());
  const hydrate = useCallback(async (rows: EventItem[]) => Promise.all(rows.map(async (row) => { const id = row.couple_photo_file_id; if (!id) return row; const cached = coverCache.current.get(id); if (cached) return { ...row, couple_photo_url: cached }; try { const url = await resolveEventCover(id); coverCache.current.set(id, url); return { ...row, couple_photo_url: url }; } catch { return row; } })), []);
  const reset = useCallback(async (blocking = !loaded.current) => { if (!userId) { setLoading(false); return; } if (resetInFlight.current || appendInFlight.current) return; resetInFlight.current = true; blocking ? setLoading(true) : setRefreshing(true); setError(''); try { const result = await fetchEventsPage(userId, 0); if (result.error) setError(result.error.message); else { const rows = await hydrate(result.data); setEvents((current) => mergeEvents(current, rows, true)); setPage(0); setHasMore(result.data.length === EVENTS_PAGE_SIZE); loaded.current = true; lastLoadedAt.current = Date.now(); } } finally { resetInFlight.current = false; setLoading(false); setRefreshing(false); } }, [hydrate, userId]);
  const append = useCallback(async () => { if (!userId || !hasMore || resetInFlight.current || appendInFlight.current) return; appendInFlight.current = true; setLoadingMore(true); setError(''); const nextPage = page + 1; try { const result = await fetchEventsPage(userId, nextPage); if (result.error) setError(result.error.message); else { const rows = await hydrate(result.data); setEvents((current) => mergeEvents(current, rows)); setPage(nextPage); setHasMore(result.data.length === EVENTS_PAGE_SIZE); } } finally { appendInFlight.current = false; setLoadingMore(false); } }, [hasMore, hydrate, page, userId]);
  const insert = useCallback(async (event: EventItem) => { const [hydrated] = await hydrate([event]); setEvents((current) => mergeEvents(current, [hydrated])); }, [hydrate]);
  return { events, loading, refreshing, loadingMore, error, setError, hasMore, reset, append, insert, shouldRefresh: () => !loaded.current || Date.now() - lastLoadedAt.current > 15000 };
}
