import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { fontSize, fontWeight, radii, shadows, spacing } from '../../theme/tokens';

export const clientsStyles = StyleSheet.create({
  heroCard: { backgroundColor: colors.text, borderRadius: radii.xl, padding: spacing.lg, gap: spacing.lg, ...shadows.elevated }, heroHeading: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, heroIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary }, heroCopy: { flex: 1, gap: 3 }, heroTitle: { color: colors.card, fontSize: fontSize.lg, fontWeight: fontWeight.bold }, heroSubtitle: { color: '#C9CED8', fontSize: fontSize.xs, lineHeight: 18 },
  primaryActionsRow: { flexDirection: 'row', alignItems: 'stretch', gap: spacing.sm }, primaryActionGrow: { flex: 1 }, templatesButton: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: spacing.md, borderRadius: radii.md, borderWidth: 1, borderColor: colors.primaryStrong, backgroundColor: colors.card }, templatesButtonText: { color: colors.primaryStrong, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  summaryRow: { flexDirection: 'row', gap: spacing.sm }, summaryMetric: { flex: 1, minWidth: 0, gap: 3 }, summaryValue: { color: colors.primary, fontSize: fontSize.xl, fontWeight: fontWeight.extrabold }, summaryLabel: { color: '#C9CED8', fontSize: 10, lineHeight: 14 },
  errorBanner: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, backgroundColor: colors.dangerBg, borderRadius: radii.md, padding: spacing.md }, errorText: { flex: 1, color: colors.dangerText, fontSize: fontSize.sm, lineHeight: 20 },
  searchWrap: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg }, searchInput: { flex: 1, color: colors.text, fontSize: fontSize.md, paddingVertical: 0 }, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, filterPill: { minHeight: 38, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radii.full, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card }, filterPillOn: { borderColor: colors.primaryStrong, backgroundColor: colors.primarySoft }, filterText: { color: colors.mutedText, fontSize: fontSize.sm, fontWeight: fontWeight.semibold }, filterTextOn: { color: colors.primaryStrong, fontWeight: fontWeight.bold },
  clientList: { gap: spacing.md }, clientCard: { backgroundColor: colors.card, borderRadius: radii.xl, borderWidth: 1, borderColor: colors.border, padding: spacing.md, gap: spacing.md, ...shadows.sm }, clientTopRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, clientIdentity: { flex: 1, minWidth: 0, gap: 4 }, clientName: { color: colors.text, fontSize: fontSize.lg, fontWeight: fontWeight.bold }, clientContext: { color: colors.mutedText, fontSize: fontSize.xs }, clientBody: { gap: 6 }, clientHelper: { color: colors.textSecondary, fontSize: fontSize.sm, lineHeight: 20 }, clientBudget: { color: colors.primaryStrong, fontSize: fontSize.md, fontWeight: fontWeight.bold }, clientActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', flexWrap: 'wrap', gap: spacing.sm }, detailButton: { minHeight: 44, justifyContent: 'center', paddingHorizontal: spacing.sm }, detailButtonText: { color: colors.textSecondary, fontSize: fontSize.sm, fontWeight: fontWeight.semibold }, primaryAction: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: spacing.md, borderRadius: radii.md, backgroundColor: colors.primary }, primaryActionText: { color: colors.primaryTextOn, fontSize: fontSize.sm, fontWeight: fontWeight.bold }, disabled: { opacity: 0.55 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15,17,21,0.58)' }, modalSheet: { maxHeight: '92%', backgroundColor: colors.surface, borderTopLeftRadius: 28, borderTopRightRadius: 28, overflow: 'hidden' }, modalHandle: { width: 44, height: 5, borderRadius: 99, alignSelf: 'center', marginTop: 10, backgroundColor: colors.borderStrong }, modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.lg, paddingVertical: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, modalTitle: { color: colors.text, fontSize: fontSize.lg, fontWeight: fontWeight.bold }, modalContent: { padding: spacing.lg, gap: spacing.md }, fieldGroup: { gap: 6 }, fieldLabel: { color: colors.textSecondary, fontSize: fontSize.xs, fontWeight: fontWeight.bold }, fieldInput: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, paddingHorizontal: spacing.md, color: colors.text, backgroundColor: colors.card, fontSize: fontSize.md }, notesInput: { minHeight: 96, paddingTop: spacing.md, textAlignVertical: 'top' }, lostButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center' }, lostButtonText: { color: colors.dangerText, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
});
