import { ActivityIndicator, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { EmptyState } from '../../components/ui/EmptyState';
import { colors } from '../../theme/colors';
import { clientsStyles as s } from './clientsScreenStyles';
import { currency, dateLabel } from './clientsScreenSelectors';
import type { ClientForm, ClientJourneyMap, ClientRow, ListFilter } from './clientsScreenTypes';

const badgeVariant = (state: string) => state === 'closed' ? 'success' as const : state === 'lost' ? 'danger' as const : state === 'signature_pending' || state === 'budget_pending' ? 'warning' as const : state === 'contract_ready' ? 'royal' as const : 'gold' as const;
export function ClientsHero({ counts }: { counts: { active: number; waiting: number; closed: number } }) { return <View style={s.heroCard}><View style={s.heroHeading}><View style={s.heroIcon}><Ionicons name="people" size={23} color={colors.text} /></View><View style={s.heroCopy}><Text style={s.heroTitle}>Jornada comercial</Text><Text style={s.heroSubtitle}>Veja quem precisa da sua atenção agora.</Text></View></View><View style={s.summaryRow}>{([['active', 'Em andamento'], ['waiting', 'Com o cliente'], ['closed', 'Fechados']] as const).map(([key, label]) => <View key={key} style={s.summaryMetric}><Text style={s.summaryValue}>{counts[key]}</Text><Text style={s.summaryLabel}>{label}</Text></View>)}</View></View>; }
export function ClientsToolbar({ search, setSearch, filter, setFilter, refreshing, refresh }: { search: string; setSearch: (v: string) => void; filter: ListFilter; setFilter: (v: ListFilter) => void; refreshing: boolean; refresh: () => void }) { return <><View style={s.searchWrap}><Ionicons name="search" size={19} color={colors.mutedText} /><TextInput style={s.searchInput} value={search} onChangeText={setSearch} placeholder="Buscar cliente" placeholderTextColor={colors.mutedText} />{refreshing ? <ActivityIndicator size="small" color={colors.primaryStrong} /> : <Pressable onPress={refresh} hitSlop={10} accessibilityLabel="Atualizar clientes"><Ionicons name="refresh" size={20} color={colors.primaryStrong} /></Pressable>}</View><View style={s.filters}>{([['active', 'Em andamento'], ['closed', 'Fechados'], ['lost', 'Perdidos']] as const).map(([value, label]) => <Pressable key={value} style={[s.filterPill, filter === value && s.filterPillOn]} onPress={() => setFilter(value)}><Text style={[s.filterText, filter === value && s.filterTextOn]}>{label}</Text></Pressable>)}</View></>; }
export function ClientsList({ clients, journeys, search, workingId, openDetails, primaryAction, create }: { clients: ClientRow[]; journeys: ClientJourneyMap; search: string; workingId: string | null; openDetails: (c: ClientRow) => void; primaryAction: (c: ClientRow) => void; create: () => void }) { if (!clients.length) return <EmptyState title={search ? 'Nenhum cliente encontrado' : 'Sua jornada começa aqui'} message={search ? 'Tente outro nome, e-mail ou telefone.' : 'Cadastre um contato para preparar o primeiro orçamento.'} actionLabel={search ? undefined : 'Cadastrar cliente'} onAction={search ? undefined : create} />; return <View style={s.clientList}>{clients.map((client) => { const journey = journeys.get(client.id)!; const working = workingId === client.id; return <View key={client.id} style={s.clientCard}><View style={s.clientTopRow}><View style={s.clientIdentity}><Text style={s.clientName} numberOfLines={1}>{client.name}</Text><Text style={s.clientContext} numberOfLines={1}>{client.event_type || 'Evento a definir'} · {dateLabel(client.event_date_expected)}</Text></View><Badge label={journey.label} variant={badgeVariant(journey.state)} /></View><View style={s.clientBody}><Text style={s.clientHelper}>{journey.helper}</Text>{client.budget_expected ? <Text style={s.clientBudget}>{currency(client.budget_expected)}</Text> : null}</View><View style={s.clientActions}><Pressable style={s.detailButton} onPress={() => openDetails(client)}><Text style={s.detailButtonText}>Ver detalhes</Text></Pressable>{journey.actionLabel ? <Pressable style={[s.primaryAction, working && s.disabled]} disabled={working} onPress={() => primaryAction(client)}>{working ? <ActivityIndicator size="small" color={colors.primaryTextOn} /> : <><Text style={s.primaryActionText}>{journey.actionLabel}</Text><Ionicons name="arrow-forward" size={16} color={colors.primaryTextOn} /></>}</Pressable> : null}</View></View>; })}</View>; }
export function ClientEditorModal({ visible, title, form, setForm, close, save, saving, markLost, bottomInset }: { visible: boolean; title: string; form: ClientForm; setForm: React.Dispatch<React.SetStateAction<ClientForm>>; close: () => void; save: () => void; saving: boolean; markLost?: () => void; bottomInset: number }) { const field = (key: keyof ClientForm) => (value: string) => setForm((current) => ({ ...current, [key]: value })); return <Modal visible={visible} transparent animationType="slide" onRequestClose={close}><KeyboardAvoidingView style={s.modalOverlay} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={[s.modalSheet, { paddingBottom: Math.max(bottomInset, 16) }]}><View style={s.modalHandle} /><View style={s.modalHeader}><Text style={s.modalTitle}>{title}</Text><Pressable onPress={close} hitSlop={10}><Ionicons name="close" size={24} color={colors.text} /></Pressable></View><ScrollView contentContainerStyle={s.modalContent} keyboardShouldPersistTaps="handled">{([['name', 'Nome *', 'Nome do cliente'], ['email', 'E-mail', 'cliente@email.com'], ['phone', 'Telefone', '(00) 00000-0000'], ['eventType', 'Tipo de evento', 'Casamento, aniversário...'], ['eventDate', 'Data prevista', 'AAAA-MM-DD'], ['budget', 'Valor estimado', '0,00']] as const).map(([key, label, placeholder]) => <View key={key} style={s.fieldGroup}><Text style={s.fieldLabel}>{label}</Text><TextInput style={s.fieldInput} value={form[key]} onChangeText={field(key)} placeholder={placeholder} placeholderTextColor={colors.mutedText} keyboardType={key === 'email' ? 'email-address' : key === 'phone' ? 'phone-pad' : key === 'budget' ? 'numeric' : 'default'} autoCapitalize={key === 'email' ? 'none' : 'sentences'} /></View>)}<Text style={s.fieldLabel}>Observações</Text><TextInput style={[s.fieldInput, s.notesInput]} value={form.notes} onChangeText={field('notes')} placeholder="O que é importante lembrar?" placeholderTextColor={colors.mutedText} multiline /><Button title="Salvar cliente" onPress={save} loading={saving} disabled={!form.name.trim()} />{markLost ? <Pressable style={s.lostButton} onPress={markLost}><Text style={s.lostButtonText}>Marcar como perdido</Text></Pressable> : null}</ScrollView></View></KeyboardAvoidingView></Modal>; }
