import { StyleSheet } from 'react-native';

import { colors } from '../../theme/colors';
import { MAP_HEIGHT, MAP_WIDTH } from './constants';

export const tableMapStyles = StyleSheet.create({
  mapLaunchCard: { minHeight: 128, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, borderRadius: 16, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.border },
  mapLaunchIcon: { width: 52, height: 52, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.card },
  mapLaunchCopy: { flex: 1, gap: 4 },
  mapLaunchTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
  card: { borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.card, padding: 10, gap: 8 },
  title: { color: colors.text, fontWeight: '700', fontSize: 14 },
  headerRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  actionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  primaryBtn: { minHeight: 34, borderRadius: 8, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary },
  primaryBtnText: { color: colors.primaryTextOn, fontWeight: '700', fontSize: 12 },
  ghostBtn: { minHeight: 34, borderRadius: 8, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card },
  ghostBtnDisabled: { opacity: 0.72 },
  ghostBtnText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  warnBtn: { minHeight: 34, borderRadius: 8, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#FECACA', backgroundColor: '#FEF2F2' },
  warnBtnText: { color: '#B91C1C', fontSize: 12, fontWeight: '700' },
  fixtureLibrary: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  fixtureChip: { flexDirection: 'row', alignItems: 'center', gap: 6, borderWidth: 1, borderColor: colors.border, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: '#F8FAFC' },
  fixtureChipText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  caption: { color: colors.mutedText, fontSize: 12, fontWeight: '600' },
  editRow: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: '#F8FAFC', padding: 10, gap: 8 },
  input: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, color: colors.text, backgroundColor: colors.card },
  loadingWrap: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, minHeight: 220, alignItems: 'center', justifyContent: 'center', gap: 8 },
  mapFrame: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: '#FFFFFF', overflow: 'hidden', minHeight: 420 },
  fullscreenMapFrame: { flex: 1, minHeight: 0 },
  gridWrap: { width: MAP_WIDTH, height: MAP_HEIGHT, backgroundColor: '#FFFFFF' },
  gridUnderlay: { ...StyleSheet.absoluteFillObject },
  gridLineV: { position: 'absolute', top: 0, bottom: 0, width: 1, backgroundColor: '#F3F4F6' },
  gridLineH: { position: 'absolute', left: 0, right: 0, height: 1, backgroundColor: '#F3F4F6' },
  tableCard: { position: 'absolute', width: 180, minHeight: 112, borderWidth: 1.5, borderRadius: 14, backgroundColor: '#FFFFFF', padding: 8, gap: 4 },
  tableTitle: { color: colors.text, fontSize: 13, fontWeight: '700' },
  tableNote: { color: colors.mutedText, fontSize: 11 },
  tableSeats: { color: colors.primaryStrong, fontSize: 11, fontWeight: '700' },
  fixtureCard: { position: 'absolute', borderWidth: 1.5, borderRadius: 12, overflow: 'hidden' },
  fixtureBody: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8, gap: 4 },
  fixtureIconBadge: { width: 26, height: 26, borderRadius: 13, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5E7EB', alignItems: 'center', justifyContent: 'center' },
  fixtureText: { color: colors.text, fontSize: 11, fontWeight: '700', textAlign: 'center' },
  fixtureDelete: { position: 'absolute', right: 4, top: 4, width: 18, height: 18, borderRadius: 9, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D1D5DB', alignItems: 'center', justifyContent: 'center' },
  fixtureDeleteText: { color: '#6B7280', fontSize: 10, fontWeight: '700' },
  modalPage: { flex: 1, backgroundColor: colors.background, padding: 12, gap: 10 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  modalHeadingCopy: { flex: 1, gap: 2 },
  modalTitle: { color: colors.text, fontSize: 19, fontWeight: '800' },
  modalSubtitle: { color: colors.mutedText, fontSize: 11, lineHeight: 15 },
  autosavePill: { flexDirection: 'row', alignItems: 'center', gap: 9, borderRadius: 12, borderWidth: 1, borderColor: '#A7F3D0', backgroundColor: '#ECFDF5', paddingHorizontal: 12, paddingVertical: 9 },
  autosavePillError: { borderColor: '#FECACA', backgroundColor: '#FEF2F2' },
  autosaveCopy: { flex: 1 },
  autosaveTitle: { color: '#047857', fontSize: 12, fontWeight: '800' },
  autosaveCaption: { color: colors.mutedText, fontSize: 10, marginTop: 1 },
  autosaveTextError: { color: '#B91C1C' },
  fullscreenToolsWrap: { gap: 6 },
  fullscreenToolsTitle: { color: colors.text, fontSize: 12, fontWeight: '800' },
  fullscreenToolsContent: { gap: 8, paddingRight: 16 },
  fullscreenToolChip: { minHeight: 38, backgroundColor: colors.card },
  fullscreenEditRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  fullscreenEditInput: { flex: 1, paddingVertical: 7 },
  exportBtn: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card },
  exportBtnText: { color: colors.text, fontSize: 12, fontWeight: '700' },
});
