export const VENDOR_CATEGORIES = ['Assessoria/Cerimonial', 'Espaço/Local', 'Buffet/Gastronomia', 'Bar/Bebidas', 'Bolo/Doces', 'Decoração/Floral', 'Foto', 'Vídeo', 'Música/DJ/Banda', 'Som/Iluminação/Estrutura', 'Locação/Mobiliário', 'Beleza/Dia da noiva', 'Trajes/Acessórios', 'Convites/Papelaria', 'Celebrante', 'Transporte/Logística', 'Lembranças/Personalizados', 'Entretenimento/Experiências', 'Conteúdo/Redes sociais', 'Outros'] as const;
export type VendorRecord = { id: string; assessor_id: string; name: string; category: string; phone: string | null; whatsapp: string | null; email: string | null; cover_image_url: string | null; cover_image_file_id: string | null; presentation_url: string | null; presentation_file_id: string | null; is_visible_in_vitrine: boolean; display_order: number; created_at: string; city: string | null; state: string | null; price_range: string | null };
export type VendorForm = { name: string; category: string; phone: string; whatsapp: string; email: string; is_visible_in_vitrine: boolean; city: string; state: string; price_range: string };
export const EMPTY_VENDOR_FORM: VendorForm = { name: '', category: 'Outros', phone: '', whatsapp: '', email: '', is_visible_in_vitrine: false, city: '', state: '', price_range: '' };
export const PRICE_RANGE_OPTIONS = [{ value: '', label: 'Selecione...' }, { value: '$', label: '$ - Econômico' }, { value: '$$', label: '$$ - Moderado' }, { value: '$$$', label: '$$$ - Premium' }, { value: '$$$$', label: '$$$$ - Luxo' }];
export function sortVendors(rows: VendorRecord[]) { return [...rows].sort((a, b) => a.display_order - b.display_order); }
export function filterVendors(rows: VendorRecord[], search: string, category: string) { const term = search.trim().toLowerCase(); return sortVendors(rows).filter((row) => (category === 'todas' || row.category === category) && (!term || `${row.name} ${row.category} ${row.phone ?? ''} ${row.whatsapp ?? ''} ${row.email ?? ''}`.toLowerCase().includes(term))); }
export function vendorPayload(form: VendorForm, id?: string) { return { id: id ?? null, name: form.name.trim(), category: form.category.trim(), phone: form.phone.trim() || null, whatsapp: form.whatsapp.trim() || null, email: form.email.trim() || null, is_visible_in_vitrine: form.is_visible_in_vitrine, city: form.city.trim() || null, state: form.state.trim() || null, price_range: form.price_range || null }; }
export function moveVendor(rows: VendorRecord[], vendorId: string, direction: 'up' | 'down') { const ordered = sortVendors(rows), index = ordered.findIndex(({ id }) => id === vendorId), swap = direction === 'up' ? index - 1 : index + 1; if (index < 0 || swap < 0 || swap >= ordered.length) return ordered; [ordered[index], ordered[swap]] = [ordered[swap], ordered[index]]; return ordered.map((vendor, display_order) => ({ ...vendor, display_order })); }
