import { StyleSheet } from 'react-native';
import { colors, gradients, radii, shadows } from '../../theme/colors';

const CARD_IMAGE_H = 104;

export const vendorCatalogStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  title: {
    color: colors.text,
    fontSize: 26,
    fontWeight: '700',
  },
  subtitle: {
    color: colors.mutedText,
    fontSize: 13,
    marginTop: 2,
  },
  addBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: gradients.gold[0],
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  errorBanner: {
    backgroundColor: colors.dangerBg,
    borderRadius: 10,
    padding: 10,
    marginHorizontal: 16,
    marginBottom: 4,
  },
  errorText: {
    color: colors.dangerText,
    fontSize: 13,
    fontWeight: '600',
  },
  searchInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: colors.text,
    backgroundColor: colors.card,
    fontSize: 14,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
  },
  categoryRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  categorySelector: {
    minHeight: 52,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.card,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  formCategorySelector: {
    marginHorizontal: 0,
    marginBottom: 0,
    backgroundColor: colors.surface,
  },
  categorySelectorTextGroup: {
    flex: 1,
  },
  categorySelectorLabel: {
    color: colors.mutedText,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 2,
  },
  categorySelectorValue: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  categoryPill: {
    minHeight: 34,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
  },
  categoryPillActive: {
    borderColor: colors.primaryStrong,
    backgroundColor: colors.primarySoft,
  },
  categoryPillText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '600',
  },
  categoryPillTextActive: {
    color: colors.primaryStrong,
  },
  listWrapper: {
    flex: 1,
  },
  listContent: {
    padding: 16,
    gap: 12,
    paddingBottom: 32,
  },
  vendorCard: {
    borderRadius: radii.lg,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    ...shadows.card,
  },
  vendorImageWrap: {
    height: CARD_IMAGE_H,
    width: '100%',
  },
  vendorImage: {
    width: '100%',
    height: '100%',
  },
  vendorImagePlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vendorImageOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 80,
  },
  vendorImageOverlayContent: {
    position: 'absolute',
    bottom: 10,
    left: 12,
    right: 12,
  },
  vendorImageName: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  vendorImageLocation: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 12,
    marginTop: 2,
  },
  vendorBadges: {
    position: 'absolute',
    top: 10,
    left: 10,
    flexDirection: 'row',
    gap: 6,
  },
  priceTag: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  priceTagText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  vendorCardBody: {
    padding: 12,
    gap: 8,
  },
  catalogContent: { flexGrow: 1 },
  catalogScroll: { flex: 1 },
  contactRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  contactAction: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactActionGreen: {
    borderColor: '#bbf7d0',
    backgroundColor: '#f0fef4',
  },
  vendorActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    paddingTop: 10,
  },
  reorderGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reorderBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reorderBtnDisabled: {
    opacity: 0.4,
  },
  orderLabel: {
    color: colors.mutedText,
    fontSize: 11,
    fontWeight: '600',
    minWidth: 26,
    textAlign: 'center',
  },
  actionGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    minHeight: 44,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  editBtnText: {
    color: colors.primaryStrong,
    fontSize: 12,
    fontWeight: '600',
  },
  deleteBtn: {
    width: 44,
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formContent: {
    gap: 8,
    paddingBottom: 8,
  },
  fieldLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 6,
  },
  textInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text,
    backgroundColor: colors.surface,
    fontSize: 14,
  },
  vitrineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  vitrineTextGroup: {
    flex: 1,
  },
  vitrineHint: {
    color: colors.mutedText,
    fontSize: 12,
    marginTop: 2,
  },
  reuseInfoCard: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginHorizontal: 16, marginBottom: 12, borderRadius: 16, borderWidth: 1, borderColor: colors.gold200, backgroundColor: colors.gold50, padding: 14 },
  reuseInfoText: { flex: 1 },
  reuseInfoTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
  reuseInfoBody: { color: colors.textSecondary, fontSize: 12, lineHeight: 18, marginTop: 3 },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 12,
  },
});
