name: Firebase Upload

on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: 'URL do APK gerado pelo EAS'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download APK
        run: curl -L -o app-release.apk "${{ github.event.inputs.apk_url }}"

      - name: Upload to Firebase
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "testers"
